"""
Autonomous Analyzer for Hledac Universal Orchestrator
======================================================

Intelligent query analysis system that automatically determines optimal research
configuration based on query content. Analyzes queries to select appropriate tools,
sources, privacy levels, and reasoning modes without manual configuration.

Features:
- Keyword-based tool detection (21+ intelligence tools)
- Automatic source inference from tool selection
- Privacy level and Tor activation determination
- ToT (Tree of Thoughts) activation recommendations
- Model selection and time estimation
- Czech language support

M1 8GB RAM Optimizations:
- Lightweight analysis with minimal memory footprint
- Efficient keyword matching with compiled regex patterns
- Lazy evaluation of complex analysis

Author: Hledac AI Research Platform
Version: 1.0.0
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple, Union

from .types import ComplexityAnalysis

logger = logging.getLogger(__name__)


@dataclass
class AutoResearchProfile:
    """
    Autonomous research configuration profile.

    Generated by AutonomousAnalyzer based on query content analysis.
    Contains all settings needed to execute an optimized research task.
    """
    # ToT Configuration
    use_tot: bool = False
    tot_mode: str = "standard"  # "standard" | "hybrid" | "full"

    # Tool Selection
    tools: Set[str] = field(default_factory=set)

    # Source Selection
    sources: Set[str] = field(default_factory=set)  # "surface" | "archive" | "academic" | "dark" | "leaked"

    # Privacy Configuration
    privacy_level: str = "STANDARD"  # "STANDARD" | "HIGH" | "MAXIMUM"
    use_tor: bool = False

    # Model Selection
    models_needed: Set[str] = field(default_factory=set)  # "hermes" | "modernbert" | "gliner"

    # Execution Parameters
    depth: str = "STANDARD"  # "QUICK" | "STANDARD" | "DEEP" | "EXHAUSTIVE"
    max_time: float = 300.0  # Estimated execution time in seconds

    # Explanation
    reasoning: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Convert profile to dictionary for serialization."""
        return {
            "use_tot": self.use_tot,
            "tot_mode": self.tot_mode,
            "tools": list(self.tools),
            "sources": list(self.sources),
            "privacy_level": self.privacy_level,
            "use_tor": self.use_tor,
            "models_needed": list(self.models_needed),
            "depth": self.depth,
            "max_time": self.max_time,
            "reasoning": self.reasoning,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AutoResearchProfile":
        """Create profile from dictionary."""
        return cls(
            use_tot=data.get("use_tot", False),
            tot_mode=data.get("tot_mode", "standard"),
            tools=set(data.get("tools", [])),
            sources=set(data.get("sources", [])),
            privacy_level=data.get("privacy_level", "STANDARD"),
            use_tor=data.get("use_tor", False),
            models_needed=set(data.get("models_needed", [])),
            depth=data.get("depth", "STANDARD"),
            max_time=data.get("max_time", 300.0),
            reasoning=data.get("reasoning", ""),
        )


class AutonomousAnalyzer:
    """
    Autonomous query analyzer for intelligent research configuration.

    Analyzes research queries to automatically determine:
    - Which intelligence tools to activate
    - Which sources to search
    - Required privacy level and Tor usage
    - Whether ToT reasoning is needed
    - Which models to load
    - Estimated execution time

    Usage:
        >>> analyzer = AutonomousAnalyzer()
        >>> profile = analyzer.analyze("Find information about Bitcoin wallet addresses on dark web")
        >>> print(profile.tools)  # {'stealth_crawler', 'blockchain_analyzer'}
        >>> print(profile.privacy_level)  # 'MAXIMUM'
        >>> print(profile.use_tor)  # True
    """

    # ==========================================================================
    # TOOL KEYWORD MAPPINGS (21 intelligence tools)
    # ==========================================================================

    TOOL_KEYWORDS: Dict[str, List[str]] = {
        # Dark Web & Stealth
        "stealth_crawler": [
            "dark web", "tor", "onion", "hidden service", ".onion",
            "darknet", "deep web", "hidden web", "temný web", "skrytá služba",
        ],

        # Archive & Historical
        "archive_discovery": [
            "archive", "wayback", "historical", "deleted", "past",
            "archiv", "historický", "smazaný", "minulost", "web archive",
            "internet archive", "snapshot", "cached",
        ],

        # Data Leaks & Breaches
        "leak_hunter": [
            "leak", "breach", "exposed", "leaked", "dump", "compromised",
            "data breach", "unik", "únik", "zveřejněný", "kompromitovaný",
            "password dump", "credential", "exposed data",
        ],

        # Blockchain & Crypto
        "blockchain_analyzer": [
            "blockchain", "crypto", "bitcoin", "ethereum", "wallet",
            "transaction", "btc", "eth", "cryptocurrency", "token",
            "smart contract", "defi", "nft", "blockchain analysis",
        ],

        # Academic & Research
        "academic_search": [
            "research", "paper", "study", "scholar", "arxiv", "academic",
            "výzkum", "studie", "článek", "publikace", "vědecký",
            "journal", "conference", "thesis", "dissertation", "peer reviewed",
        ],

        # Identity & Person Search
        "identity_stitching": [
            "identity", "person", "profile", "who is", "individual",
            "identita", "osoba", "profil", "kdo je", "jednotlivec",
            "background check", "people search", "find person",
        ],

        # Relationships & Networks
        "relationship_discovery": [
            "connection", "relationship", "network", "linked to",
            "spojení", "vztah", "síť", "propojený", "associated with",
            "affiliated", "related to", "connected to",
        ],

        # Pattern Analysis
        "pattern_mining": [
            "pattern", "trend", "anomaly", "correlation",
            "vzor", "trend", "anomálie", "korelace", "pattern analysis",
            "behavioral pattern", "usage pattern", "frequency analysis",
        ],

        # Web Intelligence
        "web_intelligence": [
            "website", "web", "online", "internet", "domain",
            "webová stránka", "web", "online", "internet", "doména",
            "site analysis", "web scraping", "web monitoring",
        ],

        # News & Media
        "news_analyzer": [
            "news", "article", "media", "report", "press",
            "novinky", "článek", "média", "zpráva", "tisk",
            "breaking news", "headline", "journalism", "news source",
        ],

        # Forums & Communities
        "forum_hunter": [
            "forum", "discussion", "community", "reddit", "thread",
            "fórum", "diskuze", "komunita", "vlákno",
            "message board", "online community", "user discussion",
        ],

        # Social Media
        "social_mapper": [
            "social media", "facebook", "twitter", "instagram", "linkedin",
            "twitter", "x.com", "tiktok", "youtube", "telegram",
            "sociální sítě", "facebook", "instagram", "linkedin",
            "social profile", "social account", "follower", "post",
        ],

        # Document Analysis
        "document_analyzer": [
            "document", "pdf", "file", "report", "doc",
            "dokument", "soubor", "zpráva", "pdf analysis",
            "document parsing", "text extraction", "file analysis",
        ],

        # Image Forensics
        "image_forensics": [
            "image", "photo", "picture", "visual", "exif",
            "obrázek", "fotografie", "foto", "vizuální",
            "image analysis", "photo analysis", "reverse image search",
        ],

        # Temporal Analysis
        "temporal_analyzer": [
            "timeline", "history", "when", "date", "time",
            "časová osa", "historie", "kdy", "datum", "čas",
            "chronology", "time series", "temporal pattern", "event sequence",
        ],

        # Geolocation
        "geolocation_tracker": [
            "location", "where", "place", "geo", "gps",
            "lokace", "kde", "místo", "geolokace", "poloha",
            "coordinates", "address", "geographic", "mapping",
        ],

        # Metadata Extraction
        "metadata_extractor": [
            "metadata", "exif", "header", "properties",
            "metadata", "hlavička", "vlastnosti", "file properties",
            "file metadata", "document properties", "technical data",
        ],

        # Threat Assessment
        "threat_assessor": [
            "threat", "risk", "danger", "malicious", "attack",
            "hrozba", "riziko", "nebezpečí", "škodlivý", "útoku",
            "security threat", "cyber threat", "risk assessment",
        ],

        # Vulnerability Scanning
        "vulnerability_scanner": [
            "vulnerability", "exploit", "cve", "security flaw",
            "zranitelnost", "exploit", "bezpečnostní chyba",
            "security vulnerability", "zero day", "patch", "bug",
        ],

        # Reputation Analysis
        "reputation_analyzer": [
            "reputation", "review", "rating", "feedback",
            "reputace", "recenze", "hodnocení", "zpětná vazba",
            "online reputation", "brand reputation", "customer review",
        ],

        # Cross-Reference & Verification
        "cross_reference_engine": [
            "cross reference", "verify", "corroborate", "confirm",
            "křížový odkaz", "ověřit", "potvrdit", "verifikovat",
            "fact check", "verification", "validate", "source verification",
        ],
    }

    # ==========================================================================
    # PRIVACY LEVEL KEYWORD MAPPINGS
    # ==========================================================================

    PRIVACY_KEYWORDS: Dict[str, List[str]] = {
        "MAXIMUM": [
            "dark web", "tor", "onion", "hidden service", "leak", "breach",
            "whistleblower", "sensitive", "classified", "confidential",
            "maximum privacy", "total anonymity", "untraceable",
            "temný web", "skrytá služba", "únik", "citlivý", "důvěrný",
        ],
        "HIGH": [
            "identity", "person", "profile", "who is", "private",
            "personal data", "pii", "high privacy", "anonymous",
            "identita", "osoba", "soukromý", "osobní údaje",
        ],
        "STANDARD": [
            # Default - no specific keywords needed
        ],
    }

    # ==========================================================================
    # SOURCE TYPE KEYWORD MAPPINGS
    # ==========================================================================

    SOURCE_KEYWORDS: Dict[str, List[str]] = {
        "surface": [
            "web", "website", "internet", "google", "search",
            "news", "article", "blog", "forum", "social media",
        ],
        "archive": [
            "archive", "wayback", "historical", "deleted", "past",
            "archiv", "historický", "snapshot", "cached",
        ],
        "academic": [
            "research", "paper", "study", "scholar", "arxiv",
            "academic", "journal", "science", "publication",
            "výzkum", "studie", "vědecký", "publikace",
        ],
        "dark": [
            "dark web", "tor", "onion", "darknet", "hidden",
            "temný web", "skrytý", "skrytá služba",
        ],
        "leaked": [
            "leak", "breach", "exposed", "dump", "compromised",
            "unik", "únik", "zveřejněný", "kompromitovaný",
        ],
    }

    # ==========================================================================
    # DEPTH LEVEL KEYWORD MAPPINGS
    # ==========================================================================

    DEPTH_KEYWORDS: Dict[str, List[str]] = {
        "EXHAUSTIVE": [
            "comprehensive", "exhaustive", "complete", "thorough",
            "everything", "all information", "full analysis", "deep dive",
            "komplexní", "exhaustivní", "úplný", "důkladný",
            "maximum detail", "in-depth", "extensive",
        ],
        "DEEP": [
            "deep", "detailed", "extensive", "comprehensive",
            "analyze", "investigation", "research", "study",
            "hluboký", "detailní", "rozsáhlý", "analýza",
            "thorough analysis", "detailed report",
        ],
        "STANDARD": [
            # Default level
        ],
        "QUICK": [
            "quick", "brief", "summary", "overview", "fast",
            "rychlý", "stručný", "přehled", "shrnutí",
            "quick check", "brief overview", "short summary",
        ],
    }

    # Tool-to-Source mapping for inference
    TOOL_SOURCE_MAPPING: Dict[str, Set[str]] = {
        "stealth_crawler": {"dark"},
        "archive_discovery": {"archive"},
        "leak_hunter": {"leaked"},
        "blockchain_analyzer": {"surface", "dark"},
        "academic_search": {"academic"},
        "identity_stitching": {"surface", "social"},
        "relationship_discovery": {"surface", "social"},
        "pattern_mining": {"surface", "archive"},
        "web_intelligence": {"surface"},
        "news_analyzer": {"surface"},
        "forum_hunter": {"surface"},
        "social_mapper": {"surface"},
        "document_analyzer": {"surface", "archive"},
        "image_forensics": {"surface"},
        "temporal_analyzer": {"surface", "archive"},
        "geolocation_tracker": {"surface"},
        "metadata_extractor": {"surface"},
        "threat_assessor": {"surface", "dark"},
        "vulnerability_scanner": {"surface", "dark"},
        "reputation_analyzer": {"surface"},
        "cross_reference_engine": {"surface", "archive", "academic"},
    }

    # Tool-to-Model mapping
    TOOL_MODEL_MAPPING: Dict[str, Set[str]] = {
        "identity_stitching": {"gliner"},
        "relationship_discovery": {"gliner"},
        "pattern_mining": {"hermes"},
        "document_analyzer": {"hermes", "modernbert"},
        "image_forensics": {"hermes"},
        "cross_reference_engine": {"hermes", "modernbert"},
        "academic_search": {"modernbert"},
    }

    def __init__(self, tot_integration: Optional[Any] = None):
        """
        Initialize AutonomousAnalyzer.

        Args:
            tot_integration: Optional TotIntegrationLayer for complexity analysis
        """
        self.tot_integration = tot_integration
        self._compiled_tool_patterns: Dict[str, List[re.Pattern]] = {}
        self._compiled_privacy_patterns: Dict[str, List[re.Pattern]] = {}
        self._compiled_source_patterns: Dict[str, List[re.Pattern]] = {}
        self._compiled_depth_patterns: Dict[str, List[re.Pattern]] = {}

        self._compile_patterns()
        logger.info("AutonomousAnalyzer initialized (v1.0.0)")

    def _compile_patterns(self) -> None:
        """Compile regex patterns for efficient matching."""
        # Compile tool patterns
        for tool, keywords in self.TOOL_KEYWORDS.items():
            self._compiled_tool_patterns[tool] = [
                re.compile(rf"\b{re.escape(keyword)}\b", re.IGNORECASE)
                for keyword in keywords
            ]

        # Compile privacy patterns
        for level, keywords in self.PRIVACY_KEYWORDS.items():
            self._compiled_privacy_patterns[level] = [
                re.compile(rf"\b{re.escape(keyword)}\b", re.IGNORECASE)
                for keyword in keywords
            ]

        # Compile source patterns
        for source, keywords in self.SOURCE_KEYWORDS.items():
            self._compiled_source_patterns[source] = [
                re.compile(rf"\b{re.escape(keyword)}\b", re.IGNORECASE)
                for keyword in keywords
            ]

        # Compile depth patterns
        for depth, keywords in self.DEPTH_KEYWORDS.items():
            self._compiled_depth_patterns[depth] = [
                re.compile(rf"\b{re.escape(keyword)}\b", re.IGNORECASE)
                for keyword in keywords
            ]

    def analyze(self, query: str) -> AutoResearchProfile:
        """
        Analyze query and generate optimal research profile.

        Args:
            query: Research query to analyze

        Returns:
            AutoResearchProfile with optimal configuration
        """
        logger.info(f"Analyzing query: {query[:100]}...")

        # Step 1: Detect tools
        tools = self._detect_tools(query)
        logger.info(f"🎯 AUTONOMOUS DECISION: Tools selected = {tools} (reason: keyword matching)")

        # Step 2: Infer sources from tools
        sources = self._infer_sources(tools, query)
        logger.info(f"🎯 AUTONOMOUS DECISION: Sources = {sources} (reason: tool-to-source inference)")

        # Step 3: Determine privacy level and Tor usage
        privacy_level, use_tor = self._determine_privacy(query, tools)
        logger.info(f"🎯 AUTONOMOUS DECISION: Privacy = {privacy_level}, Tor = {use_tor} (reason: sensitivity analysis)")

        # Step 4: Analyze complexity for ToT
        complexity, use_tot = self._analyze_complexity(query)
        logger.info(f"🎯 AUTONOMOUS DECISION: ToT = {use_tot} (complexity: {complexity:.2f})")

        # Step 5: Determine ToT mode
        tot_mode = self._determine_tot_mode(complexity)
        logger.info(f"🎯 AUTONOMOUS DECISION: ToT mode = {tot_mode}")

        # Step 6: Estimate depth
        depth = self._estimate_depth(len(tools), complexity)
        logger.info(f"🎯 AUTONOMOUS DECISION: Depth = {depth}")

        # Step 7: Create profile
        profile = AutoResearchProfile(
            use_tot=use_tot,
            tot_mode=tot_mode,
            tools=tools,
            sources=sources,
            privacy_level=privacy_level,
            use_tor=use_tor,
            depth=depth,
        )

        # Step 8: Determine models needed
        profile.models_needed = self._determine_models(profile)
        logger.info(f"🎯 AUTONOMOUS DECISION: Models = {profile.models_needed}")

        # Step 9: Estimate time
        profile.max_time = self._estimate_time(profile)
        logger.info(f"🎯 AUTONOMOUS DECISION: Max time = {profile.max_time:.0f}s")

        # Step 10: Generate reasoning
        profile.reasoning = self._generate_reasoning(profile)
        logger.info(f"🎯 AUTONOMOUS DECISION: Reasoning generated")

        return profile

    def _detect_tools(self, query: str) -> Set[str]:
        """
        Detect which intelligence tools should be activated.

        Args:
            query: Research query

        Returns:
            Set of tool names to activate
        """
        detected_tools: Set[str] = set()
        query_lower = query.lower()

        for tool, patterns in self._compiled_tool_patterns.items():
            for pattern in patterns:
                if pattern.search(query_lower):
                    detected_tools.add(tool)
                    break  # Found match for this tool, move to next

        # Always include web_intelligence as fallback for general queries
        if not detected_tools:
            detected_tools.add("web_intelligence")

        # Include cross_reference_engine for comprehensive research
        if len(detected_tools) >= 3:
            detected_tools.add("cross_reference_engine")

        return detected_tools

    def _infer_sources(self, tools: Set[str], query: str) -> Set[str]:
        """
        Infer which sources to search based on selected tools.

        Args:
            tools: Detected tools
            query: Original query

        Returns:
            Set of source types
        """
        sources: Set[str] = set()

        # Map tools to sources
        for tool in tools:
            if tool in self.TOOL_SOURCE_MAPPING:
                sources.update(self.TOOL_SOURCE_MAPPING[tool])

        # Check for explicit source keywords
        query_lower = query.lower()
        for source, patterns in self._compiled_source_patterns.items():
            for pattern in patterns:
                if pattern.search(query_lower):
                    sources.add(source)
                    break

        # Always include surface web as baseline
        sources.add("surface")

        return sources

    def _determine_privacy(self, query: str, tools: Set[str]) -> Tuple[str, bool]:
        """
        Determine privacy level and Tor activation.

        Args:
            query: Research query
            tools: Detected tools

        Returns:
            Tuple of (privacy_level, use_tor)
        """
        query_lower = query.lower()

        # Check for maximum privacy keywords
        for pattern in self._compiled_privacy_patterns.get("MAXIMUM", []):
            if pattern.search(query_lower):
                return "MAXIMUM", True

        # Check for high privacy keywords
        for pattern in self._compiled_privacy_patterns.get("HIGH", []):
            if pattern.search(query_lower):
                return "HIGH", False

        # Check tools that require high privacy
        high_privacy_tools = {"stealth_crawler", "leak_hunter", "threat_assessor"}
        if tools & high_privacy_tools:
            return "HIGH", "stealth_crawler" in tools

        return "STANDARD", False

    def _analyze_complexity(self, query: str) -> Tuple[float, bool]:
        """
        Analyze query complexity and determine ToT activation.

        Args:
            query: Research query

        Returns:
            Tuple of (complexity_score, use_tot)
        """
        # Use TotIntegrationLayer if available
        if self.tot_integration is not None:
            try:
                should_use, confidence = self.tot_integration.should_activate_tot(query)
                analysis = self.tot_integration.analyze_complexity(query)
                return analysis.score, should_use
            except Exception as e:
                logger.warning(f"ToT integration failed, using fallback: {e}")

        # Fallback: Simple complexity estimation
        return self._fallback_complexity_analysis(query)

    def _fallback_complexity_analysis(self, query: str) -> Tuple[float, bool]:
        """
        Fallback complexity analysis without ToT integration.

        Args:
            query: Research query

        Returns:
            Tuple of (complexity_score, use_tot)
        """
        query_lower = query.lower()
        words = query_lower.split()
        word_count = len(words)

        score = 0.0

        # Multi-step keywords (higher weight)
        multi_step = [
            "analyze", "compare", "evaluate", "assess", "explain",
            "determine", "investigate", "explore", "examine",
            "analyzovat", "porovnat", "zhodnotit", "vysvětlit",
        ]
        for keyword in multi_step:
            if keyword in query_lower:
                score += 0.25
                break

        # Question complexity
        question_count = query.count("?")
        score += min(0.3, question_count * 0.1)

        # Query length (more granular)
        if word_count > 50:
            score += 0.25
        elif word_count > 30:
            score += 0.2
        elif word_count > 15:
            score += 0.1

        # Alternatives/comparison (higher weight)
        alternatives = [
            "options", "pros and cons", "advantages", "alternatives",
            "compare", "versus", "vs", "trade-off", "možnosti", "výhody",
            "different approaches", "multiple strategies", "various methods",
        ]
        for keyword in alternatives:
            if keyword in query_lower:
                score += 0.2
                break

        # Multiple aspects/sub-questions indicators
        complexity_indicators = [
            "considering", "factors", "aspects", "dimensions",
            "trade-offs", "implications", "consequences", "impacts",
        ]
        for indicator in complexity_indicators:
            if indicator in query_lower:
                score += 0.15
                break

        # Multiple items to compare (comma-separated lists suggest complexity)
        comma_count = query.count(",")
        if comma_count >= 3:
            score += 0.15
        elif comma_count >= 2:
            score += 0.1

        # Cap at 1.0
        score = min(1.0, score)

        # ToT threshold
        use_tot = score >= 0.6

        return score, use_tot

    def _determine_tot_mode(self, complexity: float) -> str:
        """
        Determine ToT mode based on complexity.

        Args:
            complexity: Complexity score

        Returns:
            ToT mode string
        """
        if complexity >= 0.8:
            return "full"
        elif complexity >= 0.6:
            return "hybrid"
        return "standard"

    def _estimate_depth(self, tool_count: int, complexity: float) -> str:
        """
        Estimate research depth based on tools and complexity.

        Args:
            tool_count: Number of tools selected
            complexity: Complexity score

        Returns:
            Depth level string
        """
        # Check for explicit depth keywords
        # (This would be called with query in real implementation)

        # Score-based estimation
        depth_score = complexity + (tool_count * 0.1)

        if depth_score >= 1.0:
            return "EXHAUSTIVE"
        elif depth_score >= 0.7:
            return "DEEP"
        elif depth_score <= 0.3:
            return "QUICK"
        return "STANDARD"

    def _determine_models(self, profile: AutoResearchProfile) -> Set[str]:
        """
        Determine which models are needed based on profile.

        Args:
            profile: AutoResearchProfile

        Returns:
            Set of model names
        """
        models: Set[str] = set()

        # Map tools to models
        for tool in profile.tools:
            if tool in self.TOOL_MODEL_MAPPING:
                models.update(self.TOOL_MODEL_MAPPING[tool])

        # Always include hermes for general reasoning
        models.add("hermes")

        # Include modernbert for embedding/search tasks
        if len(profile.tools) > 2:
            models.add("modernbert")

        return models

    def _estimate_time(self, profile: AutoResearchProfile) -> float:
        """
        Estimate execution time based on profile.

        Args:
            profile: AutoResearchProfile

        Returns:
            Estimated time in seconds
        """
        base_time = 60.0  # Base 60 seconds

        # Tool multiplier
        tool_multiplier = 1.0 + (len(profile.tools) * 0.2)

        # Depth multiplier
        depth_multipliers = {
            "QUICK": 0.5,
            "STANDARD": 1.0,
            "DEEP": 2.0,
            "EXHAUSTIVE": 4.0,
        }
        depth_multiplier = depth_multipliers.get(profile.depth, 1.0)

        # ToT multiplier
        tot_multiplier = 1.5 if profile.use_tot else 1.0

        # Privacy multiplier (Tor is slower)
        privacy_multiplier = 1.3 if profile.use_tor else 1.0

        estimated_time = base_time * tool_multiplier * depth_multiplier * tot_multiplier * privacy_multiplier

        # Cap at reasonable limits
        return min(estimated_time, 1800.0)  # Max 30 minutes

    def _generate_reasoning(self, profile: AutoResearchProfile) -> str:
        """
        Generate human-readable reasoning for the profile.

        Args:
            profile: AutoResearchProfile

        Returns:
            Reasoning string
        """
        reasoning_parts = []

        # Tools reasoning
        if profile.tools:
            tool_list = ", ".join(sorted(profile.tools))
            reasoning_parts.append(f"Detected {len(profile.tools)} intelligence tools: {tool_list}")

        # Sources reasoning
        if profile.sources:
            source_list = ", ".join(sorted(profile.sources))
            reasoning_parts.append(f"Will search across {len(profile.sources)} source types: {source_list}")

        # Privacy reasoning
        if profile.privacy_level == "MAXIMUM":
            reasoning_parts.append("Maximum privacy required due to sensitive nature of query")
        elif profile.privacy_level == "HIGH":
            reasoning_parts.append("High privacy level selected for identity-related research")

        # Tor reasoning
        if profile.use_tor:
            reasoning_parts.append("Tor network enabled for anonymous access to dark web sources")

        # ToT reasoning
        if profile.use_tot:
            reasoning_parts.append(f"Tree of Thoughts ({profile.tot_mode} mode) activated for complex reasoning")

        # Depth reasoning
        if profile.depth == "EXHAUSTIVE":
            reasoning_parts.append("Exhaustive depth selected for comprehensive coverage")
        elif profile.depth == "DEEP":
            reasoning_parts.append("Deep analysis mode for thorough investigation")
        elif profile.depth == "QUICK":
            reasoning_parts.append("Quick scan mode for rapid overview")

        # Time reasoning
        reasoning_parts.append(f"Estimated execution time: {profile.max_time:.0f} seconds")

        return "; ".join(reasoning_parts)

    def get_capabilities(self) -> Dict[str, Any]:
        """Get analyzer capabilities."""
        return {
            "name": "autonomous_analyzer",
            "version": "1.0.0",
            "tools_supported": len(self.TOOL_KEYWORDS),
            "sources_supported": list(self.SOURCE_KEYWORDS.keys()),
            "privacy_levels": list(self.PRIVACY_KEYWORDS.keys()),
            "depth_levels": ["QUICK", "STANDARD", "DEEP", "EXHAUSTIVE"],
            "tot_modes": ["standard", "hybrid", "full"],
            "models": ["hermes", "modernbert", "gliner"],
            "languages": ["en", "cs"],
        }

    def health_check(self) -> bool:
        """Check if analyzer is operational."""
        try:
            # Test basic analysis
            test_profile = self.analyze("test query")
            return test_profile is not None and len(test_profile.tools) > 0
        except Exception as e:
            logger.error(f"Health check failed: {e}")
            return False


# Factory function
def create_autonomous_analyzer(tot_integration: Optional[Any] = None) -> AutonomousAnalyzer:
    """
    Create AutonomousAnalyzer with optional ToT integration.

    Args:
        tot_integration: Optional TotIntegrationLayer

    Returns:
        Configured AutonomousAnalyzer
    """
    return AutonomousAnalyzer(tot_integration)
