"""Sprint 8AS test fixtures and helpers."""
import pytest


@pytest.fixture
def sample_8ao_report():
    """Minimal report dict matching ObservedRunReport shape."""
    return {
        "started_ts": 1700000000.0,
        "finished_ts": 1700000002.0,
        "elapsed_ms": 2000.0,
        "total_sources": 5,
        "completed_sources": 1,
        "fetched_entries": 10,
        "accepted_findings": 0,
        "stored_findings": 0,
        "batch_error": None,
        "per_source": (
            {
                "feed_url": "http://example1.com/feed",
                "label": "Example1",
                "origin": "curated",
                "priority": 1,
                "fetched_entries": 5,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 500.0,
                "error": None,
            },
            {
                "feed_url": "http://example2.com/feed",
                "label": "Example2",
                "origin": "curated",
                "priority": 2,
                "fetched_entries": 0,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 100.0,
                "error": "Connection refused",
            },
        ),
        "patterns_configured": 0,
        "bootstrap_applied": False,
        "content_quality_validated": False,
        "dedup_before": {},
        "dedup_after": {},
        "dedup_delta": {},
        "dedup_surface_available": False,
        "uma_snapshot": {
            "peak_used_gib": 4.5,
            "peak_state": "normal",
            "start_state": "normal",
            "end_state": "normal",
            "sample_count": 10,
            "peak_swap_used_gib": 0.0,
        },
        "slow_sources": (
            {
                "feed_url": "http://example1.com/feed",
                "elapsed_ms": 500.0,
                "fetched_entries": 5,
            },
        ),
        "error_summary": {
            "count": 1,
            "sources": [
                {"feed_url": "http://example2.com/feed", "error": "Connection refused"},
            ],
        },
        "success_rate": 0.2,
        "failed_source_count": 4,
        "baseline_delta": {
            "completed_sources": 1,
            "completed_sources_delta": 0,
            "fetched_entries_delta": 0,
            "accepted_findings_delta": 0,
            "stored_findings_delta": 0,
            "failed_source_count": 4,
            "failed_source_count_delta": 0,
            "findings_delta": 0,
            "elapsed_ms_delta": 442.4,
            "baseline_ref": "8AO",
            "status": "stable",
            "blocker": None,
        },
        "health_breakdown": {
            "health_breakdown": {
                "success": 1,
                "network_error": 1,
                "parse_error": 0,
                "entity_recovery_related_error": 0,
                "timeout_error": 0,
                "unknown_error": 0,
            },
            "success_count": 1,
            "total": 5,
        },
    }


@pytest.fixture
def sample_8ao_improved_report():
    """Report with improved findings."""
    return {
        "started_ts": 1700000000.0,
        "finished_ts": 1700000003.0,
        "elapsed_ms": 3000.0,
        "total_sources": 5,
        "completed_sources": 3,
        "fetched_entries": 25,
        "accepted_findings": 5,
        "stored_findings": 4,
        "batch_error": None,
        "per_source": (
            {
                "feed_url": "http://example1.com/feed",
                "label": "Example1",
                "origin": "curated",
                "priority": 1,
                "fetched_entries": 10,
                "accepted_findings": 2,
                "stored_findings": 2,
                "elapsed_ms": 800.0,
                "error": None,
            },
            {
                "feed_url": "http://example2.com/feed",
                "label": "Example2",
                "origin": "curated",
                "priority": 2,
                "fetched_entries": 8,
                "accepted_findings": 1,
                "stored_findings": 1,
                "elapsed_ms": 600.0,
                "error": None,
            },
            {
                "feed_url": "http://example3.com/feed",
                "label": "Example3",
                "origin": "curated",
                "priority": 3,
                "fetched_entries": 7,
                "accepted_findings": 2,
                "stored_findings": 1,
                "elapsed_ms": 700.0,
                "error": None,
            },
            {
                "feed_url": "http://example4.com/feed",
                "label": "Example4",
                "origin": "curated",
                "priority": 4,
                "fetched_entries": 0,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 100.0,
                "error": "DNS failure",
            },
            {
                "feed_url": "http://example5.com/feed",
                "label": "Example5",
                "origin": "curated",
                "priority": 5,
                "fetched_entries": 0,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 100.0,
                "error": "Timeout",
            },
        ),
        "patterns_configured": 47,
        "bootstrap_applied": True,
        "content_quality_validated": True,
        "dedup_before": {},
        "dedup_after": {},
        "dedup_delta": {},
        "dedup_surface_available": False,
        "uma_snapshot": {
            "peak_used_gib": 4.8,
            "peak_state": "normal",
            "start_state": "normal",
            "end_state": "normal",
            "sample_count": 15,
            "peak_swap_used_gib": 0.0,
        },
        "slow_sources": (
            {
                "feed_url": "http://example1.com/feed",
                "elapsed_ms": 800.0,
                "fetched_entries": 10,
            },
        ),
        "error_summary": {
            "count": 2,
            "sources": [
                {"feed_url": "http://example4.com/feed", "error": "DNS failure"},
                {"feed_url": "http://example5.com/feed", "error": "Timeout"},
            ],
        },
        "success_rate": 0.6,
        "failed_source_count": 2,
        "baseline_delta": {
            "completed_sources": 3,
            "completed_sources_delta": 2,
            "fetched_entries_delta": 15,
            "accepted_findings_delta": 5,
            "stored_findings_delta": 4,
            "failed_source_count": 2,
            "failed_source_count_delta": -2,
            "findings_delta": 5,
            "elapsed_ms_delta": 1442.4,
            "baseline_ref": "8AO",
            "status": "improved",
            "blocker": None,
        },
        "health_breakdown": {
            "health_breakdown": {
                "success": 3,
                "network_error": 1,
                "parse_error": 0,
                "entity_recovery_related_error": 0,
                "timeout_error": 1,
                "unknown_error": 0,
            },
            "success_count": 3,
            "total": 5,
        },
    }


@pytest.fixture
def sample_network_blocked_report():
    """Report where all sources failed due to network issues."""
    return {
        "started_ts": 1700000000.0,
        "finished_ts": 1700000001.5,
        "elapsed_ms": 1500.0,
        "total_sources": 5,
        "completed_sources": 0,
        "fetched_entries": 0,
        "accepted_findings": 0,
        "stored_findings": 0,
        "batch_error": None,
        "per_source": (
            {
                "feed_url": "http://example1.com/feed",
                "label": "Example1",
                "origin": "curated",
                "priority": 1,
                "fetched_entries": 0,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 50.0,
                "error": "DNS failure",
            },
            {
                "feed_url": "http://example2.com/feed",
                "label": "Example2",
                "origin": "curated",
                "priority": 2,
                "fetched_entries": 0,
                "accepted_findings": 0,
                "stored_findings": 0,
                "elapsed_ms": 50.0,
                "error": "Connection refused",
            },
        ),
        "patterns_configured": 0,
        "bootstrap_applied": False,
        "content_quality_validated": False,
        "dedup_before": {},
        "dedup_after": {},
        "dedup_delta": {},
        "dedup_surface_available": False,
        "uma_snapshot": {
            "peak_used_gib": 3.9,
            "peak_state": "normal",
            "start_state": "normal",
            "end_state": "normal",
            "sample_count": 8,
            "peak_swap_used_gib": 0.0,
        },
        "slow_sources": (),
        "error_summary": {
            "count": 2,
            "sources": [
                {"feed_url": "http://example1.com/feed", "error": "DNS failure"},
                {"feed_url": "http://example2.com/feed", "error": "Connection refused"},
            ],
        },
        "success_rate": 0.0,
        "failed_source_count": 5,
        "baseline_delta": {
            "completed_sources": 0,
            "completed_sources_delta": -1,
            "fetched_entries_delta": -10,
            "accepted_findings_delta": 0,
            "stored_findings_delta": 0,
            "failed_source_count": 5,
            "failed_source_count_delta": 1,
            "findings_delta": 0,
            "elapsed_ms_delta": -57.6,
            "baseline_ref": "8AO",
            "status": "network_variance",
            "blocker": "no_sources_completed_no_fetched",
        },
        "health_breakdown": {
            "health_breakdown": {
                "success": 0,
                "network_error": 2,
                "parse_error": 0,
                "entity_recovery_related_error": 0,
                "timeout_error": 0,
                "unknown_error": 0,
            },
            "success_count": 0,
            "total": 5,
        },
    }
